version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - prop-ie-network

  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/prop-ie
      - JWT_SECRET=your_jwt_secret_here
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - prop-ie-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - prop-ie-network

networks:
  prop-ie-network:
    driver: bridge

volumes:
  mongodb_data:
